import { DashboardStats, Activity, Ticket, NewTicketForm } from "@/types";

export const mockTickets: Ticket[] = [
  {
    id: "REQ-001",
    title: "Fall Recruitment Instagram Campaign",
    portfolio: "Marketing",
    pointOfContact: "Sarah Chen",
    isCollaboration: true,
    collaborators: ["Alex Rivera", "Jordan Kim"],
    graphicTypes: ["Instagram Post", "Instagram Story"],
    eventName: "Fall 2025 Recruitment",
    eventDate: "2025-09-15",
    eventTime: "10:00 AM",
    eventLocation: "Student Center",
    summary:
      "Need a series of Instagram posts and stories to promote our fall recruitment event targeting new members.",
    deadline: "2025-08-31",
    creativeVision:
      "We want warm, inviting colors (oranges and yellows) with our organization\u2019s branding. Include the event date, time, and QR code to sign up. Looking for a modern, clean aesthetic with bold typography.",
    references: ["/references/inspiration-1.jpg", "/references/inspiration-2.jpg"],
    additionalRequests: "Please include both English and Spanish versions.",
    status: "In Progress",
    priority: "High",
    createdAt: "2025-06-15T10:30:00Z",
    updatedAt: "2025-06-20T14:22:00Z",
    createdBy: "Sarah Chen",
    isOnBoard: false,
  },
  {
    id: "REQ-002",
    title: "Award Certificates for Gala Night",
    portfolio: "Events",
    pointOfContact: "Marcus Johnson",
    isCollaboration: false,
    collaborators: [],
    graphicTypes: ["Award Certificate"],
    eventName: "Annual Awards Gala",
    eventDate: "2025-07-20",
    eventTime: "7:00 PM",
    eventLocation: "Grand Ballroom",
    summary:
      "Design 15 award certificates for our annual gala. Each certificate needs a unique recipient name and award category.",
    deadline: "2025-07-10",
    creativeVision:
      "Elegant, formal design with gold accents. Use our organization\u2019s official seal. Dark navy background with gold borders. Classic serif fonts.",
    references: [],
    additionalRequests: "Need a template where names can be easily edited.",
    status: "Open",
    priority: "Medium",
    createdAt: "2025-06-18T09:15:00Z",
    updatedAt: "2025-06-18T09:15:00Z",
    createdBy: "Marcus Johnson",
    isOnBoard: false,
  },
  {
    id: "REQ-003",
    title: "Tech Workshop LinkedIn Banner",
    portfolio: "Tech",
    pointOfContact: "Priya Patel",
    isCollaboration: true,
    collaborators: ["Tech Team"],
    graphicTypes: ["LinkedIn Post"],
    eventName: "Intro to Web Development Workshop",
    eventDate: "2025-07-05",
    eventTime: "2:00 PM",
    eventLocation: "Engineering Building Room 204",
    summary:
      "Create a LinkedIn banner and post for our upcoming intro to web development workshop.",
    deadline: "2025-06-28",
    creativeVision:
      "Tech/modern aesthetic with dark mode colors. Include code snippets in the background. Use the organization\u2019s tech portfolio colors. Clean, minimal design.",
    references: [],
    additionalRequests: "",
    status: "In Review",
    priority: "Urgent",
    createdAt: "2025-06-12T16:45:00Z",
    updatedAt: "2025-06-22T11:00:00Z",
    createdBy: "Priya Patel",
    isOnBoard: false,
  },
  {
    id: "REQ-005",
    title: "Internal Meeting Presentation Template",
    portfolio: "Internal",
    pointOfContact: "David Kim",
    isCollaboration: false,
    collaborators: [],
    graphicTypes: ["Other"],
    eventName: "Weekly Team Meetings",
    eventDate: "2025-06-25",
    eventTime: "5:00 PM",
    eventLocation: "Virtual (Zoom)",
    summary:
      "Need a reusable Google Slides template for our weekly internal team meetings.",
    deadline: "2025-06-23",
    creativeVision:
      "Clean, professional with our branding. Should have sections for agenda, updates, action items. Not too flashy - functional first.",
    references: [],
    additionalRequests: "Should work well in both light and dark mode.",
    status: "Open",
    priority: "Low",
    createdAt: "2025-06-19T13:00:00Z",
    updatedAt: "2025-06-19T13:00:00Z",
    createdBy: "David Kim",
    isOnBoard: false,
  },
  {
    id: "REQ-006",
    title: "youCode Hackathon Promo Video",
    portfolio: "youCode",
    pointOfContact: "Maya Rodriguez",
    isCollaboration: true,
    collaborators: ["Marketing Team"],
    graphicTypes: ["Instagram Reel/TikTok"],
    eventName: "youCode Hackathon 2025",
    eventDate: "2025-08-10",
    eventTime: "9:00 AM",
    eventLocation: "Innovation Lab",
    summary:
      "Create a promotional Reel/TikTok for our annual hackathon. Fast-paced, energetic content.",
    deadline: "2025-07-25",
    creativeVision:
      "Energetic and youthful. Green and black color scheme. Show clips of coding, team collaboration, and fun moments from last year. Trending music overlay.",
    references: [],
    additionalRequests: "Vertical format for TikTok. Keep under 60 seconds.",
    status: "In Progress",
    priority: "High",
    createdAt: "2025-06-10T11:20:00Z",
    updatedAt: "2025-06-21T09:45:00Z",
    createdBy: "Maya Rodriguez",
    isOnBoard: false,
  },
  {
    id: "REQ-007",
    title: "Data Infographic for Annual Report",
    portfolio: "Data",
    pointOfContact: "James Liu",
    isCollaboration: true,
    collaborators: ["Presidential", "Marketing"],
    graphicTypes: ["LinkedIn Post"],
    eventName: "Annual Report Release",
    eventDate: "2025-07-01",
    eventTime: "12:00 PM",
    eventLocation: "Online",
    summary:
      "Create an infographic summarizing our organization\u2019s yearly impact metrics, membership growth, and event reach.",
    deadline: "2025-06-25",
    creativeVision:
      "Data-driven design with charts and graphs. Use our brand palette. Clean, modern infographic style. Should be scannable and shareable on LinkedIn.",
    references: [],
    additionalRequests:
      "Will provide exact numbers closer to deadline. Need editable format.",
    status: "Open",
    priority: "High",
    createdAt: "2025-06-17T14:30:00Z",
    updatedAt: "2025-06-17T14:30:00Z",
    createdBy: "James Liu",
    isOnBoard: false,
  },
  {
    id: "REQ-008",
    title: "Presidential Campaign Social Kit",
    portfolio: "Presidential",
    pointOfContact: "Olivia Martinez",
    isCollaboration: true,
    collaborators: ["Marketing", "Events"],
    graphicTypes: ["Instagram Post", "Instagram Story", "LinkedIn Post"],
    eventName: "Presidential Elections 2025",
    eventDate: "2025-09-01",
    eventTime: "8:00 AM",
    eventLocation: "Campus Wide",
    summary:
      "Full social media kit for the upcoming presidential elections. Include candidate profile cards, voting reminders, and results announcement templates.",
    deadline: "2025-08-15",
    creativeVision:
      "Professional, trustworthy, and engaging. Red, white, and blue color scheme with modern touches. Must be impartial - no candidate bias in design.",
    references: [],
    additionalRequests:
      "Need templates that can be quickly customized for each candidate.",
    status: "In Review",
    priority: "Urgent",
    createdAt: "2025-06-14T10:00:00Z",
    updatedAt: "2025-06-22T16:30:00Z",
    createdBy: "Olivia Martinez",
  },
  {
    id: "REQ-004",
    title: "Thank You Cards for Sponsors",
    portfolio: "External",
    pointOfContact: "Emily Watson",
    isCollaboration: false,
    collaborators: [],
    graphicTypes: ["Thank You Card"],
    eventName: "Sponsorship Drive 2025",
    eventDate: "2025-08-01",
    eventTime: "All Day",
    eventLocation: "N/A",
    summary:
      "Design thank you cards to be sent to our 2025 sponsors. Need both digital and print-ready versions.",
    deadline: "2025-07-15",
    creativeVision:
      "Professional and grateful tone. Use our brand colors (navy and white). Leave space for handwritten messages. Clean, elegant design.",
    references: [],
    additionalRequests:
      "Need version for platinum, gold, and silver sponsors with slight variations.",
    status: "Completed",
    priority: "Medium",
    createdAt: "2025-05-20T08:00:00Z",
    updatedAt: "2025-06-10T15:30:00Z",
    createdBy: "Emily Watson",
    isOnBoard: false,
  },
];

// ─── Mock Dashboard Stats ───
export const mockStats: DashboardStats = {
  total: 8,
  open: 3,
  inProgress: 2,
  inReview: 2,
  completed: 1,
  urgent: 2,
};

// ─── Mock Activity ───
export const mockActivities: Activity[] = [
  {
    id: "act-1",
    type: "status_change",
    ticketId: "REQ-001",
    ticketTitle: "Fall Recruitment Instagram Campaign",
    description: "moved from Open to In Progress",
    timestamp: "2025-06-20T14:22:00Z",
    user: "Alex Rivera",
  },
  {
    id: "act-2",
    type: "created",
    ticketId: "REQ-005",
    ticketTitle: "Internal Meeting Presentation Template",
    description: "created this request",
    timestamp: "2025-06-19T13:00:00Z",
    user: "David Kim",
  },
  {
    id: "act-3",
    type: "status_change",
    ticketId: "REQ-003",
    ticketTitle: "Tech Workshop LinkedIn Banner",
    description: "moved from In Progress to In Review",
    timestamp: "2025-06-22T11:00:00Z",
    user: "Priya Patel",
  },
  {
    id: "act-4",
    type: "priority_change",
    ticketId: "REQ-008",
    ticketTitle: "Presidential Campaign Social Kit",
    description: "marked as Urgent",
    timestamp: "2025-06-22T16:30:00Z",
    user: "Olivia Martinez",
  },
  {
    id: "act-5",
    type: "completed",
    ticketId: "REQ-004",
    ticketTitle: "Thank You Cards for Sponsors",
    description: "marked as Completed",
    timestamp: "2025-06-10T15:30:00Z",
    user: "Emily Watson",
  },
  {
    id: "act-6",
    type: "created",
    ticketId: "REQ-007",
    ticketTitle: "Data Infographic for Annual Report",
    description: "created this request",
    timestamp: "2025-06-17T14:30:00Z",
    user: "James Liu",
  },
];

// ─── Mock User ───
export const mockUser = {
  name: "Ellie Lan",
  email: "ellie@org.edu",
  avatar: null,
};

// ─── Default form values ───
export const defaultFormValues: NewTicketForm = {
  portfolio: null,
  pointOfContact: "",
  isCollaboration: false,
  collaborators: [],
  graphicTypes: [],
  eventName: "",
  eventDate: "",
  eventTime: "",
  eventLocation: "",
  summary: "",
  deadline: "",
  creativeVision: "",
  references: [],
  additionalRequests: "",
};

