import { DashboardStats, Activity, Ticket, NewTicketForm } from "@/types";

export const mockTickets: Ticket[] = [
    {
    id: "REQ-009",
    title: "Summer Internships & Adventures Recap",
    portfolio: "Marketing",
    pointOfContact: "Ella Ilan",
    isCollaboration: true,
    collaborators: ["Presidential"],
    graphicTypes: ["Instagram Post", "Instagram Carousel"],
    otherGraphicType: "",
    eventName: "Summer Recap",
    eventTime: "12:00 PM",
    eventLocation: "Instagram",
    summary:
      "Create a carousel highlighting what our members have been up to over the summer, including internships, research, travel, conferences, and personal achievements before welcoming everyone back for the school year.",
    deadline: "2026-09-03",
    creativeVision:
      "Bright, fun, scrapbook aesthetic with candid photos, location stickers, and playful typography. Focus on celebrating community and showcasing diverse experiences.",
    references: [],
    additionalRequests:
      "Collect photos from members by August 28. Include a final slide welcoming everyone back to campus.",
    status: "Open",
    priority: "High",
    createdAt: "2026-07-04T10:00:00Z",
    updatedAt: "2026-07-04T10:00:00Z",
    createdBy: "Ella Ilan",
    isOnBoard: false,
  },
  {
    id: "REQ-010",
    title: "DataFest Recap Post",
    portfolio: "Events",
    pointOfContact: "Ella Ilan",
    isCollaboration: true,
    collaborators: ["Data Team"],
    graphicTypes: ["Instagram Post", "LinkedIn Post"],
    otherGraphicType: "",
    eventName: "DataFest",
    eventTime: "5:00 PM",
    eventLocation: "Online",
    summary:
      "Create a recap post celebrating our members who participated in DataFest, highlighting team photos, accomplishments, and memorable moments from the competition.",
    deadline: "2026-07-10",
    creativeVision:
      "Modern, data-inspired graphics with bold typography, event branding, and statistics overlays. Keep it energetic and professional.",
    references: [],
    additionalRequests:
      "Include team placements if available and tag participating members.",
    status: "Open",
    priority: "Medium",
    createdAt: "2026-07-04T10:05:00Z",
    updatedAt: "2026-07-04T10:05:00Z",
    createdBy: "Ella Ilan",
    isOnBoard: false,
  },
  {
    id: "REQ-011",
    title: "Data Science Meme TikTok #1",
    portfolio: "Marketing",
    pointOfContact: "Ella Ilan",
    isCollaboration: false,
    collaborators: [],
    graphicTypes: ["Instagram Reel/TikTok"],
    otherGraphicType: "",
    eventName: "September Social Content",
    eventTime: "6:00 PM",
    eventLocation: "TikTok",
    summary:
      "Produce a short, relatable meme TikTok about the realities of being a data science student.",
    deadline: "2026-08-28",
    creativeVision:
      "Trending audio, fast cuts, self-deprecating humour, captions, and campus footage.",
    references: [],
    additionalRequests:
      "Aim for under 20 seconds and reuse a trending TikTok format.",
    status: "Open",
    priority: "Low",
    createdAt: "2026-07-04T10:10:00Z",
    updatedAt: "2026-07-04T10:10:00Z",
    createdBy: "Ella Ilan",
    isOnBoard: false,
  },
  {
    id: "REQ-012",
    title: "Data Science Meme TikTok #2",
    portfolio: "Marketing",
    pointOfContact: "Ella Ilan",
    isCollaboration: false,
    collaborators: [],
    graphicTypes: ["Instagram Reel/TikTok"],
    otherGraphicType: "",
    eventName: "September Social Content",
    eventTime: "6:00 PM",
    eventLocation: "TikTok",
    summary:
      "Create another meme TikTok focused on debugging, Python, or late-night assignment struggles.",
    deadline: "2026-09-04",
    creativeVision:
      "Highly relatable student humour using a currently trending meme format.",
    references: [],
    additionalRequests: "Keep editing quick and caption-heavy.",
    status: "Open",
    priority: "Low",
    createdAt: "2026-07-04T10:15:00Z",
    updatedAt: "2026-07-04T10:15:00Z",
    createdBy: "Ella Ilan",
    isOnBoard: false,
  },
  {
    id: "REQ-013",
    title: "Data Science Meme TikTok #3",
    portfolio: "Marketing",
    pointOfContact: "Ella Ilan",
    isCollaboration: false,
    collaborators: [],
    graphicTypes: ["Instagram Reel/TikTok"],
    otherGraphicType: "",
    eventName: "September Social Content",
    eventTime: "6:00 PM",
    eventLocation: "TikTok",
    summary:
      "Produce the final September meme TikTok featuring data science stereotypes, imposter syndrome, or SQL jokes.",
    deadline: "2026-09-11",
    creativeVision:
      "Funny, fast-paced, and highly shareable with a punchline in the last few seconds.",
    references: [],
    additionalRequests:
      "Encourage engagement with a question in the caption.",
    status: "Open",
    priority: "Low",
    createdAt: "2026-07-04T10:20:00Z",
    updatedAt: "2026-07-04T10:20:00Z",
    createdBy: "Ella Ilan",
    isOnBoard: false,
  },
  {
    id: "REQ-014",
    title: "Meet the Team Campaign",
    portfolio: "Marketing",
    pointOfContact: "Ella Ilan",
    isCollaboration: true,
    collaborators: ["Internal"],
    graphicTypes: ["Instagram Carousel", "Instagram Story"],
    otherGraphicType: "",
    eventName: "Meet the Team",
    eventTime: "12:00 PM",
    eventLocation: "Instagram",
    summary:
      "Design a carousel introducing this year's executive team with photos, roles, fun facts, and what each person is excited about this year.",
    deadline: "2026-09-08",
    creativeVision:
      "Consistent branded template with clean layouts, playful icons, and a welcoming tone. Feature each executive on their own slide.",
    references: [],
    additionalRequests:
      "Collect headshots and fun facts from all executives before design begins.",
    status: "Open",
    priority: "High",
    createdAt: "2026-07-04T10:25:00Z",
    updatedAt: "2026-07-04T10:25:00Z",
    createdBy: "Ella Ilan",
    isOnBoard: false,
  },
];

// ─── Mock User ───
export const mockUser = {
  name: "Ellie Lan",
  email: "ellie@org.edu",
  avatar: null,
};

// ─── Default form values ───
export const defaultFormValues: NewTicketForm = {
  portfolio: null,
  pointOfContact: "",
  graphicTypes: [],
  otherGraphicType: "",
  eventName: "",
  eventTime: "",
  eventLocation: "",
  summary: "",
  deadline: "",
  creativeVision: "",
  references: [],
  additionalRequests: "",
};

